In [1]:
import numpy as np

In [2]:
x=[1,2,3,4,5,6,7,8,9,10]

In [3]:
type(x)

list

In [4]:
arr=np.array(x)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.arange(1,11,3) # start, stop, step

array([ 1,  4,  7, 10])

In [11]:
np.zeros((3,4)) # 3 rows, 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Zeros and ones are widely used in cv


In [12]:
np.ones((3,4)) # 3 rows, 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr1=np.random.randint(1,1000,50) # 50 random integers between 1 and 1000
arr1

array([870, 564, 297, 993, 963, 533,   9, 774, 722, 175, 660, 232, 336,
       819, 173, 426, 860,  19, 975, 234, 877, 462, 381, 410, 683, 762,
         2, 507, 780, 630, 646, 840, 375, 551, 605, 305, 508, 840, 344,
       106, 574, 566,  84, 666, 287, 994, 592,  22, 979, 522], dtype=int32)

When seed value is not given then random value always get changes

In [14]:

arr1=np.random.randint(1,1000,50) # 50 random integers between 1 and 1000
arr1


array([915, 285, 632, 870, 409,  55, 984, 451, 651, 744, 674, 951, 471,
       367,  35, 613, 888, 554, 932, 732, 211, 550, 274, 691, 338, 839,
       801, 520, 295, 853, 847, 943,  76,  23, 362,  72,   5, 751, 735,
       266, 908, 945, 164,  99, 904, 164, 129, 148, 765, 178], dtype=int32)

In [17]:
np.random.seed(42) # for reproducibility
arr1=np.random.randint(1,1000,50) # 50 random integers between 1 and 1000
arr1

array([103, 436, 861, 271, 107,  72, 701,  21, 615, 122, 467, 215, 331,
       459,  88, 373, 100, 872, 664, 131, 662, 309, 770, 344, 492, 414,
       806, 386, 192, 956, 277, 161, 460, 314,  22, 253, 748, 857, 561,
       475,  59, 511, 682, 476, 700, 976, 783, 190, 958, 687], dtype=int32)

In [19]:
arr1  #as seed value is given then random value always get same

array([103, 436, 861, 271, 107,  72, 701,  21, 615, 122, 467, 215, 331,
       459,  88, 373, 100, 872, 664, 131, 662, 309, 770, 344, 492, 414,
       806, 386, 192, 956, 277, 161, 460, 314,  22, 253, 748, 857, 561,
       475,  59, 511, 682, 476, 700, 976, 783, 190, 958, 687], dtype=int32)

In [21]:
np.random.seed(16) # for reproducibility
arr2=np.random.randint(1,100,(3,4)) # 3 rows, 4 columns
arr2

array([[42, 70, 66, 69],
       [32,  5, 42, 97],
       [17, 31, 59, 19]], dtype=int32)

In [22]:
arr1.reshape(5,10) # 5 rows, 10 columns

array([[103, 436, 861, 271, 107,  72, 701,  21, 615, 122],
       [467, 215, 331, 459,  88, 373, 100, 872, 664, 131],
       [662, 309, 770, 344, 492, 414, 806, 386, 192, 956],
       [277, 161, 460, 314,  22, 253, 748, 857, 561, 475],
       [ 59, 511, 682, 476, 700, 976, 783, 190, 958, 687]], dtype=int32)

In [27]:
arr2.reshape(2,6) # 2rows, 6 columns    #This will work only if total number of elements are same e.g. 3*4=12 and 2*6=12

array([[42, 70, 66, 69, 32,  5],
       [42, 97, 17, 31, 59, 19]], dtype=int32)

In [53]:
#Everything in one line
arr3=np.random.randint(0,1000,50).reshape(5,10) # 50 random integers between 1 and 1000, reshaped to 5 rows, 10 columns
arr3

array([[470,  63, 122, 397,  81, 448, 931, 575, 354, 818],
       [922, 983, 302, 870,  23, 601, 848, 367,  82, 886],
       [578, 487, 107,  22, 121, 632,  94, 166, 402, 854],
       [433, 248, 123, 933, 656,  60,  65, 554, 258, 821],
       [203, 330, 880, 543, 182, 781, 193, 681, 496, 994]], dtype=int32)

In [54]:
print(arr3.max())
print(arr3.min())

994
22


In [55]:
arr3.mean()

np.float64(460.8)

In [56]:
print(arr3.argmax()) # index of maximum value

print(arr3.argmin()) # index of minimum value

49
23


In [57]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(50,)
(3, 4)
(5, 10)


In [58]:
row=0
column=0
print(arr3[row,column]) # access element at row 0, column 0

470


In [59]:
print(arr3[:,column])
print(arr3[row,:]) # access all columns of row 0

[470 922 578 433 203]
[470  63 122 397  81 448 931 575 354 818]


In [60]:
print(arr3[1:3, 2:5]) # access rows 1 to 2 and columns 2 to 4

[[302 870  23]
 [107  22 121]]


In [61]:
arr3[1:3, 2:5]=0
arr3

array([[470,  63, 122, 397,  81, 448, 931, 575, 354, 818],
       [922, 983,   0,   0,   0, 601, 848, 367,  82, 886],
       [578, 487,   0,   0,   0, 632,  94, 166, 402, 854],
       [433, 248, 123, 933, 656,  60,  65, 554, 258, 821],
       [203, 330, 880, 543, 182, 781, 193, 681, 496, 994]], dtype=int32)

In [64]:
arr5=arr3.copy() # create a copy of arr3

In [65]:
arr5

array([[470,  63, 122, 397,  81, 448, 931, 575, 354, 818],
       [922, 983,   0,   0,   0, 601, 848, 367,  82, 886],
       [578, 487,   0,   0,   0, 632,  94, 166, 402, 854],
       [433, 248, 123, 933, 656,  60,  65, 554, 258, 821],
       [203, 330, 880, 543, 182, 781, 193, 681, 496, 994]], dtype=int32)